<div>
<form action="" method="get">
区县选择：
<select name="areaid">
<?php 
foreach ($area_list as $key=>$value){?>
<option value ="1,8,553,<?=$value['locid']?>"><?=$value['type_name']?></option>
<?php 
}
?>
</select>
入住时间:<input type="text" name ="sdate" value="<?=date('Y-m-d',time());?>" />
退房时间:<input type="text" name ="edate" value="<?=date('Y-m-d',time()+86400);?>"/>
<button type="submit">搜索</button>
</form>
</div>


<div class="tb">

<div class="nav_bar">
<div class="nav">民宿名称</div>
<div class="nav">房间类型</div>
<div class="nav">民宿地址</div>
<div class="nav">入住时间</div>
<div class="nav">房间数量</div>
</div>

<?php
foreach ($idleroom_list as $key=>$value){
?>
<div class="nav_bar">
<div class="nav"><a href="http://taiwan.kangkanghui.com/h/<?=$arr_room[$value['nid']]['uid']?>" target="_blank" ><?=$arr_stay[$arr_room[$value['nid']]['uid']]['title']?></a></div>
<div class="nav"><?=$arr_room[$value['nid']]['title']?></div>
<div class="nav"><?=$arr_stay[$arr_room[$value['nid']]['uid']]['address']?></div>
<div class="nav"><?=$value['room_date']?></div>
<div class="nav">剩余 <?=$value['idlenum']?> 空房</div>
</div>
<?php 
}
?>
</div>